server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #通过微服务名访问，lb是默认的协议名
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤工厂增加请求头
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            # - After=2020-12-28T10:59:34.102+08:00[Asia/Shanghai]
            # - Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            # - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头包含“X-Request-Id”
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka