server:
  port: 7015
spring:
  application:
    name: ware-drool-rule
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/rule-engine?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: geminisaga
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: entities